language: python
python:
  - 2.7
install:
# Switch off virtualenv so we can use apt-get for Python packages
  - deactivate

# add repo
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3E5C1192
  - sudo apt-get update

# install binary deps
  - sudo apt-get install python-numpy python-matplotlib cython gfortran
  - sudo apt-get install libudunits2-dev libhdf5-serial-dev netcdf-bin libnetcdf-dev

# instal packages in pip
  - sudo pip install -H netCDF4
  - sudo pip install -Hr test_requirements.txt
  - python setup.py build_ext --inplace

script:
  - py.test reflexible -v --cov reflexible --cov-report term-missing
  # reflexible is far from being PEP8 compatible yet, but in the future maybe wise to use the line below...
  # - py.test reflexible --pep8 reflexible -v --cov reflexible --cov-report term-missing
after_success:
  - coveralls
notifications:
  email: false
