language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt -r test_requirements.txt
  - pip install coveralls
  - python setup.py build_ext --inplace
script:
  - py.test
after_success:
  - coveralls
notifications:
  email: false
